services:
  postgres:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: llama
      POSTGRES_PASSWORD: llama_pw
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U llama"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgvector_data:
